name: personal_docker_ros2_jazzy

services:
  jinsoo_docker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: jinsoo
        USER_UID: ${HOST_UID:-1000}
        USER_GID: ${HOST_GID:-1000}

    image: personal-ros2-jazzy:latest
    container_name: jinsoo_pc
    hostname: ros2-jazzy-docker

    privileged: true
    network_mode: host
    ipc: host

    stdin_open: true
    tty: true

    environment:
      DISPLAY: ${DISPLAY}
      QT_X11_NO_MITSHM: "1"
      LIBGL_ALWAYS_SOFTWARE: ${LIBGL_ALWAYS_SOFTWARE:-0}
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-30}
      RMW_IMPLEMENTATION: ${RMW_IMPLEMENTATION:-rmw_fastrtps_cpp}
      RCUTILS_COLORIZED_OUTPUT: "1"
      HISTFILE: /home/jinsoo/.bash_history
      AUTO_COLCON_BUILD: ${AUTO_COLCON_BUILD:-1}
      PERSONAL_WS: /home/jinsoo/ros2_ws
      OPEN_MANIPULATOR_WS: /root/ros2_ws

    volumes:
      # 호스트와 Docker가 함께 수정하는 소스
      - ./ros2_ws/src:/home/jinsoo/ros2_ws/src

      # Docker가 관리하는 빌드 결과
      - ros2_build:/home/jinsoo/ros2_ws/build
      - ros2_install:/home/jinsoo/ros2_ws/install
      - ros2_log:/home/jinsoo/ros2_ws/log

      # 사용자 설정
      - ./persistent/config:/home/jinsoo/.config
      - ./persistent/ros:/home/jinsoo/.ros
      - ./persistent/cache:/home/jinsoo/.cache
      - ./persistent/local:/home/jinsoo/.local
      - ./persistent/gz:/home/jinsoo/.gz
      - ./persistent/bash_history:/home/jinsoo/.bash_history

      # X11 GUI
      - /tmp/.X11-unix:/tmp/.X11-unix:rw

      # USB, 카메라, 시리얼 장치
      - /dev:/dev
      - /run/udev:/run/udev:ro

    working_dir: /home/jinsoo/ros2_ws

    command: ["sleep", "infinity"]

volumes:
  ros2_build:
  ros2_install:
  ros2_log:
